config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  get "home/about"
  
  devise_for :users
  resources :comrades
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comrade.rb
class Comrade < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comrades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comrades_controller.rb
class ComradesController < ApplicationController
  before_action :set_comrade, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]

  # GET /comrades or /comrades.json
  def index
    @comrades = Comrade.all
  end

  # GET /comrades/1 or /comrades/1.json
  def show
  end

  # GET /comrades/new
  def new
    # @comrade = Comrade.new
    @comrade = current_user.comrades.build
  end

  # GET /comrades/1/edit
  def edit
  end

  # POST /comrades or /comrades.json
  def create
    # @comrade = Comrade.new(comrade_params)
    @comrade = current_user.comrades.build(comrade_params)

    respond_to do |format|
      if @comrade.save
        format.html { redirect_to comrade_url(@comrade), notice: "Comrade was successfully created." }
        format.json { render :show, status: :created, location: @comrade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comrade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comrades/1 or /comrades/1.json
  def update
    respond_to do |format|
      if @comrade.update(comrade_params)
        format.html { redirect_to comrade_url(@comrade), notice: "Comrade was successfully updated." }
        format.json { render :show, status: :ok, location: @comrade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comrade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comrades/1 or /comrades/1.json
  def destroy
    @comrade.destroy
    respond_to do |format|
      format.html { redirect_to comrades_url, notice: "Comrade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @comrade = current_user.comrades.find_by(id: params[:id])
    redirect_to comrades_path, notice: "Not Authorized To Perfom Action On This Comrade" if @comrade.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comrade
      @comrade = Comrade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comrade_params
      params.require(:comrade).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comrades_helper.rb
module ComradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comrades/_comrade.html.erb
<div id="<%= dom_id comrade %>">
  <p>
    <strong>First name:</strong>
    <%= comrade.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= comrade.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= comrade.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= comrade.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= comrade.twitter %>
  </p>

  

</div>

app/views/comrades/_form.html.erb
<%= form_with(model: comrade) do |form| %>
  <% if comrade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comrade.errors.count, "error") %> prohibited this comrade from being saved:</h2>

      <ul>
        <% comrade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Email address" %>
  </div>

  <div class="form-group">
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone number" %>
  </div>

  <div class="form-group">
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter handle" %>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id, id: :comrade_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>


  <div >
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comrades/edit.html.erb
<h1>Editing comrade</h1>

<%= render "form", comrade: @comrade %>

<br>

<div>
  <%= link_to "Show this comrade", @comrade %> |
  <%= link_to "Back to comrades", comrades_path %>
</div>

app/views/comrades/index.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead class="bg-dark bg-opacity-50">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Twitter</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @comrades.each do |comrade| %>
        <% if comrade.user == current_user %>
          <tr>
            <td>
              <%= link_to comrade.first_name + " " + comrade.last_name, comrade %>
            </td>
            <td><%= comrade.email %></td>
            <td><%= comrade.phone %></td>
            <td><%= comrade.twitter %></td>
            <td><%= link_to "Edit", edit_comrade_path(comrade), class: "btn btn-secondary btn-sm" %>|<%= link_to "Delete", comrade_path(comrade), data: { turbo_method: :delete, turbo_confirm: "Are you sure"}, class: "btn btn-danger btn-sm" %>
          </tr>
        <% end %><br>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New comrade", new_comrade_path, class: "btn btn-secondary" %>
</div>

app/views/comrades/new.html.erb
<div class="container p-5"><h1>New comrade</h1>
<br>
<%= render "form", comrade: @comrade %>

<br>

<div>
  <%= link_to "Back", comrades_path %>
</div>
</div>

app/views/comrades/show.html.erb
<div class="container">
  <div class="jumbotron bg-primary" id="jumbotron">
    <h1 class="display-4">
      <%= @comrade.first_name %>
      <%= @comrade.last_name %>
    </h1>
    <p class="lead">
      <%= @comrade.email %>    |
      <%= @comrade.phone %>    |
      <%= @comrade.twitter %>  
    </p>
    <hr class="my-4">
    <div>
      <%= link_to "Edit", edit_comrade_path(@comrade), class: "btn btn-dark" %>
      <%= link_to "Back", comrades_path, class: "btn btn-primary" %>
      <%= link_to "Destroy", comrade_path(@comrade), data: { turbo_method: :delete, turbo_confirm: "Are you sure"}, class: " btn btn-dark" %>
    </div>
  </div>
</div>

app/views/home/_nav.html.erb

<nav class="navbar sticky-top navbar-expand-lg bg-primfary bg-opfacity-75" id="navbar">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Home", root_path, class: "navbar-brand text-white"%>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
      <%= link_to "about us", home_about_path, class: "nav-link text-white" %>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "comrades", comrades_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add comrade", new_comrade_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sing Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure"}, class: "nav-link text-white" %>
      </li>
    
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link text-white" %>
      </li>
    <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container-fluid" id="about_page">
  <div id="story"><h1>About Us</h1></div>
  <div id="story">---OUR STORY---</div>
  <div>Just over a year ago, we became fascinated by the idea of discovering the world through 
    someone's eyes. What if you could see through the eyes of a protester in Ukraine? Or 
    watch the sunrise from a hot air balloon in Cappadocia? It may sound crazy, but we 
    wanted to build the closest thing to teleportation. While there are many ways to 
    discover events and places, we realized there is no better way to experience a place 
    right now than through live video. A picture may be worth a thousand words, but live 
    video can take you someplace and show you around.</div>
</div>

app/views/home/index.html.erb
<div class="container-fluid" id="home_page">
  <div class="align-items-start pt-3">
    <h1 class="text-white">Welcome to our community.</h1>
    <h3 class="text-white pe-5 fw-light fst-italic">A community built on integrity, loyalty, trust, empathy, dependability confidence for one another.</h3>
    
    <h2 class="justify-content-center text-success pt-3">Here we share true comradeship.<h2>
  </div>

  <% if user_signed_in? %>
  <div></div>
  <% else %>
  <div class="d-flex gap-4">
    <div id="log-in"><%= link_to "Sign In", new_user_session_path, class: "btn text-white" %></div>
    <div id="sign-in"><%= link_to "Sign Up", new_user_registration_path, class: "btn text-white" %></div>
  </div>
  <% end %>

</div>

<div>
  <div class="text-white fw-lighter" id="copyright">Copyright 2022 by UkwuomaFortune</div>
</div>

app/views/layouts/_alerts.html.erb

<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Comrades</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
  
  <%= render 'home/nav' %>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </body>
</html>